import budget
from budget import create_spend_chart
food = budget.Category("Food")
food.deposit(1000, "initial deposit")
food.withdraw(10.15, "groceries")
food.withdraw(150, "restaurant and more food for dessert")
print(food.get_balance())
clothing = budget.Category("Clothing")
food.transfer(50, clothing)
clothing.withdraw(25.55)
clothing.withdraw(100)
auto = budget.Category("Auto")
auto.deposit(1000, "initial deposit")
auto.withdraw(15)
tech = budget.Category("Tech")
tech.deposit(1000, "initial deposit")
tech.withdraw(15)
tech.withdraw(100,"New cover for my phone")
print(food)
print(clothing)
print(tech)
print(create_spend_chart([food, clothing, auto,tech]))
# Run unit tests automatically
#main(module='test_module', exit=False)